Adds DomainEventHandler a priority property to control execution order
seedstack/business pull request #105
Opened 2019-05-20 09:54 UTC by Sherpard

DomainEventHandlers execution order now can be defined by a property "priority"

By Default, priority is 1

2019-06-04 09:22 UTC, adrienlauer commented
Thank you for the nice work !

What do you think about using a`@Priority` annotation on the `DomainEventHandler`s to order them instead of an explicit method in the interface ? This annotation is the JSR standard one and is already used in various places of the framework where absolute ordering among classes is necessary.

2019-06-04 11:05 UTC, Sherpard commented
That was my first approach, not with standard means, but by adding a priority property @ DomainEventHandler.

Anyway, due to the nature of Events, there could be a need for different logics when handling different events, (Thinking on child events and so on), Maybe we can make a @Priority interceptor the default implementation,

2019-06-05 09:02 UTC, Sherpard commented
> Thank you for the nice work !
> 
> What do you think about using a`@Priority` annotation on the `DomainEventHandler`s to order them instead of an explicit method in the interface ? This annotation is the JSR standard one and is already used in various places of the framework where absolute ordering among classes is necessary.

I've updated the PR to use @Priority instead of getPriority() property from DomainEventHandler Inteface :)  way cleaner

2019-06-06 08:30 UTC, ejemba commented on core/src/test/java/org/seedstack/business/fixtures/event/interceptors/DefaultPriorityEventHandler.java
> +
I would add javadoc explaining the role of this class.

2019-06-06 08:30 UTC, ejemba commented on specs/src/main/java/org/seedstack/business/domain/DomainEventInterceptor.java
> +public interface DomainEventInterceptor {
I would add javadoc explaining the role of this interface.

2019-06-06 11:09 UTC, Sherpard commented on core/src/test/java/org/seedstack/business/fixtures/event/interceptors/DefaultPriorityEventHandler.java
> +
This is a test case, but already added some javadoc :)

2019-06-06 11:10 UTC, Sherpard commented on specs/src/main/java/org/seedstack/business/domain/DomainEventInterceptor.java
> +public interface DomainEventInterceptor {
added javadoc 👍

2019-06-07 08:40 UTC, adrienlauer requested changes
Please reflect the latest changes in the changelog.

2019-06-24 11:11 UTC, Sherpard commented
> Please reflect the latest changes in the changelog.

Already updated the changelog, :)

2019-12-17 15:27 UTC, closed without merging

2019-12-17 15:28 UTC, Sherpard commented
Already merged on #108

2019-12-17 15:28 UTC, adrienlauer commented
Merged through #108